-- DROP DATABASE IF EXISTS academy;
-- CREATE DATABASE academy;

-- CREATE DATABASE IF NOT EXISTS academy;

USE academy;

-- ESERCIZIO 1

SELECT FIRST_NAME, LAST_NAME
FROM employees;

SELECT DISTINCT DEPARTMENT_ID
FROM departments;

-- ESERCIZIO 2

SELECT SUBSTRING(FIRST_NAME,1,3) AS ACRONYM
FROM employees;

-- ESERCIZIO 3

SELECT FIRST_NAME, LAST_NAME, SALARY
FROM employees
WHERE SALARY NOT BETWEEN 10000 AND 15000;

-- ESERCIZIO 4

SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_ID
FROM employees
WHERE DEPARTMENT_ID IN (30,100)
ORDER BY FIRST_NAME;

-- ESERCIZIO 5

SELECT FIRST_NAME, LAST_NAME, HIRE_DATE
FROM employees
WHERE YEAR(HIRE_DATE) = 1987;

-- ESERCIZIO 6

SELECT FIRST_NAME, LAST_NAME
FROM employees
WHERE LENGTH(FIRST_NAME) = 6;

-- ESERCIZIO 7

SELECT *
FROM employees
WHERE LAST_NAME IN ("Jones","Scott","Blake","King","Ford");

-- ESERCIZIO 8

SELECT *
FROM employees
ORDER BY FIRST_NAME DESC;

SELECT FIRST_NAME, LAST_NAME, SALARY, (SALARY + (SALARY * COMMISSION_PCT)) AS GROSS_SALARY
FROM employees;